# Site settings
title: "Open Collector"
email: bery08@gmail.com
description: "Norbert Berenyi's personal blog."
baseurl: ""
url: "http://norbert-berenyi.github.io/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  norbert-berenyi
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
